# Generated by Django 5.1.15 on 2026-04-10 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('content', models.TextField()),
                ('context_summary', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insights_insight',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'insight_type', '-generated_at'], name='insights_in_user_id_cab480_idx')],
            },
        ),
    ]
