# Generated by Django 5.1.15 on 2026-04-05 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_course_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('room', models.CharField(blank=True, default='', max_length=255)),
                ('course_state', models.CharField(blank=True, default='', max_length=50)),
                ('alternate_link', models.URLField(blank=True, default='')),
                ('teacher_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_json', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_course',
                'unique_together': {('user', 'google_course_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], default='started', max_length=20)),
                ('courses_synced', models.IntegerField(default=0)),
                ('coursework_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_coursework_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('work_type', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('alternate_link', models.URLField(blank=True, default='')),
                ('raw_json', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursework_items', to='classroom.course')),
            ],
            options={
                'db_table': 'classroom_coursework',
                'unique_together': {('course', 'google_coursework_id')},
            },
        ),
    ]
